// Privacy Policy page (route: "/privacy").
// Plain-English notice describing what the contact form collects and how it's
// used. Linked from the footer. NOTE: this is a reasonable starting draft —
// have it reviewed before relying on it legally.
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Vantgrove",
  description: "How Vantgrove collects and handles personal information.",
};

export default function PrivacyPage() {
  return (
    <section className="mx-auto max-w-3xl px-6 py-24">
      <h1 className="text-4xl font-semibold tracking-tight text-foreground">
        Privacy Policy
      </h1>
      <p className="mt-4 text-sm text-muted">Last updated: June 2026</p>

      <div className="mt-10 space-y-10 leading-8 text-muted">
        <div>
          <p>
            This Privacy Policy explains how Vantgrove (&ldquo;we,&rdquo;
            &ldquo;us&rdquo;) collects and handles personal information when you
            visit vantgrove.com or contact us through this website. We keep our
            data practices deliberately minimal.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Information we collect
          </h2>
          <p className="mt-3">
            We only collect the information you choose to give us through our
            contact form:
          </p>
          <ul className="mt-3 space-y-2">
            {[
              "Your name",
              "Your email address",
              "Your organization (optional)",
              "The contents of your message",
            ].map((item) => (
              <li key={item} className="flex gap-3">
                <span
                  aria-hidden
                  className="mt-3 h-1.5 w-1.5 flex-none rounded-full bg-brand"
                />
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="mt-3">
            Like most websites, our hosting provider may also automatically log
            basic technical information (such as IP address and browser type) for
            security and operational purposes.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            How we use your information
          </h2>
          <p className="mt-3">
            We use the information you submit solely to read and respond to your
            inquiry. We do not sell your information, and we do not use it for
            advertising or automated marketing.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Service providers
          </h2>
          <p className="mt-3">
            We rely on a small number of trusted third parties to operate this
            website:
          </p>
          <ul className="mt-3 space-y-2">
            <li className="flex gap-3">
              <span
                aria-hidden
                className="mt-3 h-1.5 w-1.5 flex-none rounded-full bg-brand"
              />
              <span>
                <strong className="font-medium text-foreground">Vercel</strong>{" "}
                hosts the website and may process technical log data.
              </span>
            </li>
            <li className="flex gap-3">
              <span
                aria-hidden
                className="mt-3 h-1.5 w-1.5 flex-none rounded-full bg-brand"
              />
              <span>
                <strong className="font-medium text-foreground">Resend</strong>{" "}
                delivers the email generated by our contact form.
              </span>
            </li>
          </ul>
          <p className="mt-3">
            These providers process information on our behalf and are not
            permitted to use it for their own purposes.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Cookies and tracking
          </h2>
          <p className="mt-3">
            This website does not use advertising cookies or third-party
            analytics, and it does not track you across other websites.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Data retention
          </h2>
          <p className="mt-3">
            We keep contact messages only as long as needed to respond to your
            inquiry and maintain our records. You may ask us to delete your
            information at any time.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Your rights
          </h2>
          <p className="mt-3">
            Depending on where you live, you may have the right to access,
            correct, or delete the personal information we hold about you. To
            make a request, contact us using the details below.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-semibold tracking-tight text-foreground">
            Contact us
          </h2>
          <p className="mt-3">
            For any questions about this policy or your information, email us at{" "}
            <a
              href="mailto:hello@vantgrove.com"
              className="font-medium text-brand transition-colors hover:text-brand-dark"
            >
              hello@vantgrove.com
            </a>
            .
          </p>
        </div>
      </div>
    </section>
  );
}
